package com.qbdlx.mobile

import com.qbdlx.mobile.api.Album
import com.qbdlx.mobile.api.ArtistRef
import com.qbdlx.mobile.api.Track
import com.qbdlx.mobile.download.MetadataTagger
import kotlinx.serialization.json.JsonPrimitive
import org.jaudiotagger.audio.AudioFileIO
import org.jaudiotagger.tag.FieldKey
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Exercises the real JAudioTagger code path against a real audio file.
 *
 * Tagging was the component that broke downloads: it ran before the file was
 * published, and a throw there meant the user got nothing. These tests pin both
 * halves of the fix — that tagging works, and that a failure is survivable.
 */
class MetadataTaggerTest {

    private val album = Album(
        id = JsonPrimitive("alb1"),
        title = "Kind of Blue",
        release_date_original = "1959-08-17",
        tracks_count = 5,
        upc = "5099749534728",
        copyright = "(C) 1959 Columbia Records",
        product_type = "album",
        artist = ArtistRef(name = "Miles Davis"),
        artists = listOf(ArtistRef(name = "Miles Davis")),
        label = com.qbdlx.mobile.api.LabelRef(name = "Columbia"),
        genre = com.qbdlx.mobile.api.Genre(name = "Jazz"),
    )

    private val track = Track(
        id = JsonPrimitive("trk1"),
        title = "So What",
        track_number = 1,
        media_number = 1,
        media_count = 1,
        isrc = "USSM15900111",
        duration = 545,
        parental_warning = false,
    )

    /**
     * Copies the committed FLAC fixture to a scratch file so each test starts
     * from a pristine, real audio file.
     *
     * The fixture is a genuine FLAC (real framing, STREAMINFO, CRCs, verbatim
     * subframes) generated by `tools/gen_flac.py`, not a renamed stub.
     */
    private fun makeFlac(name: String): File {
        val source = File(javaClass.classLoader!!.getResource("sample.flac")!!.toURI())
        val dest = File.createTempFile(name, ".flac")
        dest.deleteOnExit()
        source.copyTo(dest, overwrite = true)
        assertTrue("FLAC fixture must be copied", dest.length() > 0)
        // Sanity: the fixture must be readable by the same reader the tagger uses.
        assertNotNull("FLAC fixture must parse", AudioFileIO.read(dest).audioHeader)
        return dest
    }

    private fun scratch(name: String): File =
        File.createTempFile(name, ".flac").also {
            it.delete()
            it.deleteOnExit()
        }

    @Test
    fun `tags are written and readable back from a real flac`() {
        val flac = makeFlac("tags")
        val working = scratch("tags-work")

        val result = MetadataTagger.tag(
            file = flac,
            album = album,
            track = track,
            coverArt = null,
            options = MetadataTagger.Options(),
            workingCopy = working,
        )

        assertTrue("tagging should succeed: ${result.warning}", result.ok)

        val read = AudioFileIO.read(working)
        val tag = read.tag
        assertNotNull("file must have a tag after tagging", tag)
        assertEquals("So What", tag.getFirst(FieldKey.TITLE))
        assertEquals("Kind of Blue", tag.getFirst(FieldKey.ALBUM))
        assertEquals("Miles Davis", tag.getFirst(FieldKey.ALBUM_ARTIST))
        assertEquals("Miles Davis", tag.getFirst(FieldKey.ARTIST))
        assertEquals("Jazz", tag.getFirst(FieldKey.GENRE))
        assertEquals("USSM15900111", tag.getFirst(FieldKey.ISRC))
        assertEquals("5099749534728", tag.getFirst(FieldKey.BARCODE))
        assertEquals("1", tag.getFirst(FieldKey.TRACK))
        assertEquals("5", tag.getFirst(FieldKey.TRACK_TOTAL))
        assertEquals("1959", tag.getFirst(FieldKey.YEAR))
        assertEquals("Columbia", tag.getFirst(FieldKey.RECORD_LABEL))
    }

    @Test
    fun `audio survives tagging and stays decodable`() {
        val flac = makeFlac("audio")
        val working = scratch("audio-work")
        val before = AudioFileIO.read(flac).audioHeader

        val result = MetadataTagger.tag(
            flac, album, track, null, MetadataTagger.Options(), working,
        )
        assertTrue(result.ok)

        val after = AudioFileIO.read(working).audioHeader
        assertEquals(
            "sample rate must not change",
            before.sampleRate, after.sampleRate,
        )
        assertEquals(
            "channel count must not change",
            before.channels, after.channels,
        )
    }

    @Test
    fun `the original file is left untouched because tagging works on a copy`() {
        val flac = makeFlac("original")
        val sizeBefore = flac.length()
        val bytesBefore = flac.readBytes()
        val working = scratch("orig-work")

        MetadataTagger.tag(flac, album, track, null, MetadataTagger.Options(), working)

        assertEquals("original size must not change", sizeBefore, flac.length())
        assertTrue("original bytes must not change", bytesBefore.contentEquals(flac.readBytes()))
    }

    @Test
    fun `a corrupt file reports failure instead of throwing`() {
        val garbage = File.createTempFile("garbage", ".flac")
        garbage.deleteOnExit()
        garbage.writeBytes(ByteArray(4096) { 0x41 })

        val working = scratch("garbage-work")

        // Must not throw: the caller publishes the untouched download instead.
        val result = MetadataTagger.tag(
            garbage, album, track, null, MetadataTagger.Options(), working,
        )
        assertFalse("corrupt input must not report success", result.ok)
        assertNotNull("a reason must be surfaced to the user", result.warning)
    }

    @Test
    fun `tagging with no metadata is a clean failure`() {
        val flac = makeFlac("nometa")
        val working = scratch("nometa-work")
        val result = MetadataTagger.tag(
            flac, null, null, null, MetadataTagger.Options(), working,
        )
        assertFalse(result.ok)
        assertNotNull(result.warning)
    }

    @Test
    fun `cover art is embedded and readable back`() {
        val flac = makeFlac("art")
        val working = scratch("art-work")

        val result = MetadataTagger.tag(
            flac, album, track, coverJpeg(), MetadataTagger.Options(writeCoverArt = true), working,
        )

        assertNull("cover art should embed cleanly: ${result.warning}", result.warning)
        assertTrue(result.ok)

        val art = AudioFileIO.read(working).tag.firstArtwork
        assertNotNull("cover art must survive the write", art)
        assertEquals("image/jpeg", art.mimeType)
        assertTrue("cover art bytes must be present", (art.binaryData?.size ?: 0) > 0)
        assertTrue("audio must still exist", working.length() > 0)
    }

    @Test
    fun `an invalid image degrades to a warning rather than failing the download`() {
        val flac = makeFlac("badart")
        val working = scratch("badart-work")

        // Structurally a JPEG container, but not a decodable image: JAudioTagger
        // tries to build a BufferedImage and rejects it.
        val notAnImage = byteArrayOf(
            0xFF.toByte(), 0xD8.toByte(), 0xFF.toByte(), 0xE0.toByte(),
            0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00,
            0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00,
            0xFF.toByte(), 0xD9.toByte(),
        )

        val result = MetadataTagger.tag(
            flac, album, track, notAnImage, MetadataTagger.Options(writeCoverArt = true), working,
        )

        // Either it embedded something, or it warned — but the audio must
        // survive and the tags must still be applied.
        assertTrue("audio must still exist", working.length() > 0)
        assertTrue("tags must still be written", result.ok || result.warning != null)
        val reread = AudioFileIO.read(working)
        assertEquals("So What", reread.tag.getFirst(FieldKey.TITLE))
    }

    /**
     * Real 16x16 baseline JPEG generated by `tools/gen_jpeg.py`.
     *
     * A structurally-fake JPEG is not enough: FlacTag.createField decodes the
     * bytes into a BufferedImage and throws if that fails.
     */
    private fun coverJpeg(): ByteArray =
        javaClass.classLoader!!.getResourceAsStream("cover.jpg")!!.use { it.readBytes() }
}
